export const NEW_ORDER_REQUEST = "NEW_ORDER_REQUEST";
export const NEW_ORDER_SUCCESS = "NEW_ORDER_SUCCESS";
export const NEW_ORDER_FAIL = "NEW_ORDER_FAIL";

export const MY_ORDERS_REQUEST = "MY_ORDERS_REQUEST";
export const MY_ORDERS_SUCCESS = "MY_ORDERS_SUCCESS";
export const MY_ORDERS_FAIL = "MY_ORDERS_FAIL";

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";

export const PAYMENT_STATUS_REQUEST = "PAYMENT_STATUS_REQUEST";
export const PAYMENT_STATUS_SUCCESS = "PAYMENT_STATUS_SUCCESS";
export const PAYMENT_STATUS_FAIL = "PAYMENT_STATUS_FAIL";

export const ALL_ORDERS_REQUEST = "ALL_ORDERS_REQUEST";
export const ALL_ORDERS_SUCCESS = "ALL_ORDERS_SUCCESS";
export const ALL_ORDERS_FAIL = "ALL_ORDERS_FAIL";

export const UPDATE_ORDER_REQUEST = "UPDATE_ORDER_REQUEST";
export const UPDATE_ORDER_SUCCESS = "UPDATE_ORDER_SUCCESS";
export const UPDATE_ORDER_RESET = "UPDATE_ORDER_RESET";
export const UPDATE_ORDER_FAIL = "UPDATE_ORDER_FAIL";

export const DELETE_ORDER_REQUEST = "DELETE_ORDER_REQUEST";
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS";
export const DELETE_ORDER_RESET = "DELETE_ORDER_RESET";
export const DELETE_ORDER_FAIL = "DELETE_ORDER_FAIL";

export const SEARCH_ORDERS_REQUEST = "SEARCH_ORDERS_REQUEST";
export const SEARCH_ORDERS_SUCCESS = "SEARCH_ORDERS_SUCCESS";
export const SEARCH_ORDERS_FAIL = "SEARCH_ORDERS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

// --- TRACKING AND RECENT ORDERS ---
export const GET_RECENT_ORDERS_REQUEST = "GET_RECENT_ORDERS_REQUEST";
export const GET_RECENT_ORDERS_SUCCESS = "GET_RECENT_ORDERS_SUCCESS";
export const GET_RECENT_ORDERS_FAIL = "GET_RECENT_ORDERS_FAIL";

export const GET_USER_RECENT_ORDERS_REQUEST = "GET_USER_RECENT_ORDERS_REQUEST";
export const GET_USER_RECENT_ORDERS_SUCCESS = "GET_USER_RECENT_ORDERS_SUCCESS";
export const GET_USER_RECENT_ORDERS_FAIL = "GET_USER_RECENT_ORDERS_FAIL";

export const ADD_TRACKING_EVENT_REQUEST = "ADD_TRACKING_EVENT_REQUEST";
export const ADD_TRACKING_EVENT_SUCCESS = "ADD_TRACKING_EVENT_SUCCESS";
export const ADD_TRACKING_EVENT_FAIL = "ADD_TRACKING_EVENT_FAIL";
export const ADD_TRACKING_EVENT_RESET = "ADD_TRACKING_EVENT_RESET";

// --- ADDED FOR REAL-TIME UPDATE ---
export const NEW_ORDER_RECEIVED = "NEW_ORDER_RECEIVED";

// --- SAMPLE ORDER CONSTANTS ---
export const NEW_SAMPLE_ORDER_REQUEST = "NEW_SAMPLE_ORDER_REQUEST";
export const NEW_SAMPLE_ORDER_SUCCESS = "NEW_SAMPLE_ORDER_SUCCESS";
export const NEW_SAMPLE_ORDER_FAIL = "NEW_SAMPLE_ORDER_FAIL";

export const MY_SAMPLE_ORDERS_REQUEST = "MY_SAMPLE_ORDERS_REQUEST";
export const MY_SAMPLE_ORDERS_SUCCESS = "MY_SAMPLE_ORDERS_SUCCESS";
export const MY_SAMPLE_ORDERS_FAIL = "MY_SAMPLE_ORDERS_FAIL";

export const ORDER_SHIPPING_DETAILS_REQUEST = "ORDER_SHIPPING_DETAILS_REQUEST";
export const ORDER_SHIPPING_DETAILS_SUCCESS = "ORDER_SHIPPING_DETAILS_SUCCESS";

// Order shipping details
export const ORDER_SHIPPING_DETAILS_FAIL = "ORDER_SHIPPING_DETAILS_FAIL";