export const GET_MY_QUOTES_REQUEST = 'GET_MY_QUOTES_REQUEST';
export const GET_MY_QUOTES_SUCCESS = 'GET_MY_QUOTES_SUCCESS';
export const GET_MY_QUOTES_FAIL = 'GET_MY_QUOTES_FAIL';

export const GET_QUOTE_DETAILS_REQUEST = 'GET_QUOTE_DETAILS_REQUEST';
export const GET_QUOTE_DETAILS_SUCCESS = 'GET_QUOTE_DETAILS_SUCCESS';
export const GET_QUOTE_DETAILS_FAIL = 'GET_QUOTE_DETAILS_FAIL';

export const CREATE_QUOTE_REQUEST = 'CREATE_QUOTE_REQUEST';
export const CREATE_QUOTE_SUCCESS = 'CREATE_QUOTE_SUCCESS';
export const CREATE_QUOTE_FAIL = 'CREATE_QUOTE_FAIL';

export const UPDATE_QUOTE_STATUS_REQUEST = 'UPDATE_QUOTE_STATUS_REQUEST';
export const UPDATE_QUOTE_STATUS_SUCCESS = 'UPDATE_QUOTE_STATUS_SUCCESS';
export const UPDATE_QUOTE_STATUS_FAIL = 'UPDATE_QUOTE_STATUS_FAIL';

export const CLEAR_QUOTE_ERRORS = 'CLEAR_QUOTE_ERRORS';
