// Comprehensive list of Indian cities, towns, and urban areas across all states and union territories
export const indianCities = [
    // Major Metropolitan Cities
    'Mumbai', 'Delhi', 'Bangalore', 'Hyderabad', 'Ahmedabad',
    'Chennai', 'Kolkata', 'Surat', 'Pune', 'Jaipur',
    'Lucknow', 'Kanpur', 'Nagpur', 'Indore', 'Thane',
    'Bhopal', 'Visakhapatnam', 'Pimpri-Chinchwad', 'Patna', 'Vadodara',
    'Ghaziabad', 'Ludhiana', 'Agra', 'Nashik', 'Faridabad',
    'Meerut', 'Rajkot', 'Kalyan-Dombivli', 'Vasai-Virar', 'Varanasi',
    'Srinagar', 'Aurangabad', 'Dhanbad', 'Amritsar', 'Navi Mumbai',
    'Prayagraj (Allahabad)', 'Ranchi', 'Howrah', 'Jabalpur', 'Gwalior',
    'Vijayawada', 'Jodhpur', 'Madurai', 'Raipur', 'Kota',
    'Guwahati', 'Chandigarh', 'Solapur', 'Hubli-Dharwad', 'Mysore',
    'Tiruchirappalli', 'Bareilly', 'Aligarh', 'Tiruppur', 'Gurugram (Gurgaon)',
    'Moradabad', 'Jalandhar', 'Bhubaneswar', 'Salem', 'Warangal',
    'Guntur', 'Bhiwandi', 'Saharanpur', 'Gorakhpur', 'Bikaner',
    'Amravati', 'Noida', 'Jamshedpur', 'Bhilai', 'Cuttack',
    'Firozabad', 'Kochi', 'Nellore', 'Bhavnagar', 'Dehradun',
    'Durgapur', 'Asansol', 'Rourkela', 'Nanded', 'Kolhapur',
    'Ajmer', 'Akola', 'Gulbarga', 'Jamnagar', 'Ujjain',
    'Loni', 'Siliguri', 'Jhansi', 'Ulhasnagar', 'Jammu',
    'Sangli-Miraj & Kupwad', 'Mangalore', 'Erode', 'Belgaum', 'Ambattur',
    'Tirunelveli', 'Malegaon', 'Gaya', 'Jalgaon', 'Udaipur',
    'Maheshtala', 'Davanagere', 'Kozhikode', 'Kurnool', 'Rajpur Sonarpur',
    'Rajahmundry', 'Bokaro', 'South Dumdum', 'Ballari (Bellary)', 'Patiala',
    'Gopalpur', 'Agartala', 'Bhagalpur', 'Muzaffarnagar', 'Bhatpara',
    'Panihati', 'Latur', 'Dhule', 'Rohtak', 'Korba', 'Bhilwara',
  
    // Additional Major Cities and State Capitals
    'Thiruvananthapuram', 'Coimbatore', 'Tirupati', 'Vijayapura', 'Shimla',
    'Imphal', 'Aizawl', 'Kohima', 'Shillong', 'Itanagar',
    'Gangtok', 'Kavaratti', 'Port Blair', 'Silvassa', 'Daman',
    'Puducherry', 'Karaikal', 'Yanam', 'Mahe', 'Panaji',
    'Dispur',
  
    // Important District Headquarters and Major Towns
    'Alappuzha', 'Almora', 'Alwar', 'Anand', 'Anantapur',
    'Anantnag', 'Araria', 'Aruppukkottai', 'Baharampur', 'Balaghat',
    'Balangir', 'Baleshwar', 'Balrampur', 'Banda', 'Baramati',
    'Baramulla', 'Baran', 'Baraut', 'Bardhaman', 'Bargarh',
    'Baripada', 'Barmer', 'Barnala', 'Basti', 'Bathinda',
    'Beed', 'Begusarai', 'Berhampur', 'Bettiah', 'Bhadohi',
    'Bhadrak', 'Bhandara', 'Bharatpur', 'Bharuch', 'Bhatapara',
    'Bhind', 'Bhiwani', 'Bhongir', 'Bhuj', 'Bidar',
    'Bihar Sharif', 'Bijapur', 'Bijnor', 'Bilaspur', 'Bishnupur',
    'Biswanath', 'Bodinayakanur', 'Bongaigaon', 'Budaun', 'Bulandshahr',
    'Buldhana', 'Bundi', 'Burhanpur', 'Buxar', 'Chamba',
    'Chamoli', 'Champawat', 'Champhai', 'Chandauli', 'Chandel',
    'Chandrapur', 'Charaideo', 'Charkhi Dadri', 'Chatra', 'Chengalpattu',
    'Chhapar', 'Chhatarpur', 'Chhindwara', 'Chikballapur', 'Chikmagalur',
    'Chirang', 'Chitradurga', 'Chittoor', 'Chittorgarh', 'Churachandpur',
    'Churu', 'Cooch Behar', 'Cuddalore', 'Dahod', 'Dakshin Dinajpur',
    'Dakshina Kannada', 'Damoh', 'Darbhanga', 'Darjeeling', 'Darrang',
    'Datia', 'Dausa', 'Deoghar', 'Deoria', 'Dewas',
    'Dhalai', 'Dhamtari', 'Dhar', 'Dharmapuri', 'Dhemaji',
    'Dhenkanal', 'Dholpur', 'Dibrugarh', 'Dimapur', 'Dindigul',
    'Dindori', 'Diu', 'Dumka', 'Dungarpur', 'East Champaran',
    'East Godavari', 'East Kameng', 'East Khasi Hills', 'East Siang', 'Eluru',
    'Ernakulam', 'Etah', 'Etawah', 'Faridkot', 'Farrukhabad',
    'Fatehabad', 'Fatehgarh Sahib', 'Fatehpur', 'Fazilka', 'Firozpur',
    'Gadag', 'Gadchiroli', 'Gajapati', 'Ganderbal', 'Ganjam',
    'Garhwa', 'Gautam Buddha Nagar', 'Giridih', 'Goalpara', 'Godda',
    'Golaghat', 'Gomati', 'Gondia', 'Gopalganj', 'Gurdaspur',
    'Hailakandi', 'Hamirpur', 'Hanumangarh', 'Hapur', 'Harda',
    'Hardoi', 'Haridwar', 'Hassan', 'Hathras', 'Haveri',
    'Hazaribagh', 'Hingoli', 'Hisar', 'Hojai', 'Hoshangabad',
    'Hoshiarpur', 'Idukki', 'Imphal East', 'Imphal West', 'Jagatsinghpur',
    'Jagtial', 'Jaisalmer', 'Jajpur', 'Jalaun', 'Jalna',
    'Jalpaiguri', 'Jamtara', 'Jamui', 'Jangaon', 'Janjgir-Champa',
    'Jashpur', 'Jaunpur', 'Jehanabad', 'Jhabua', 'Jhajjar',
    'Jhalawar', 'Jhargram', 'Jharsuguda', 'Jhunjhunu', 'Jind',
    'Jogulamba Gadwal', 'Jorhat', 'Junagadh', 'Kabirdham', 'Kadapa',
    'Kaimur', 'Kaithal', 'Kalahandi', 'Kalimpong', 'Kallakurichi',
    'Kamareddy', 'Kamjong', 'Kamle', 'Kamrup', 'Kamrup Metropolitan',
    'Kanchipuram', 'Kandhamal', 'Kangpokpi', 'Kangra', 'Kannauj',
    'Kannur', 'Kanpur Dehat', 'Kanyakumari', 'Kapurthala', 'Karauli',
    'Karbi Anglong', 'Kargil', 'Karimganj', 'Karimnagar', 'Karnal',
    'Karur', 'Kasaragod', 'Kasganj', 'Kathua', 'Katihar',
    'Katni', 'Kaushambi', 'Kendrapara', 'Kendujhar', 'Khagaria',
    'Khammam', 'Khandwa', 'Kharagpur', 'Khargone', 'Kheda',
    'Khowai', 'Khunti', 'Khurda', 'Kinnaur', 'Kiphire',
    'Kishanganj', 'Kishtwar', 'Kodagu', 'Koderma', 'Kokrajhar',
    'Kolar', 'Kolasib', 'Kollam', 'Kondagaon', 'Koppal',
    'Koraput', 'Koriya', 'Kottayam', 'Kra Daadi', 'Krishna',
    'Krishnagiri', 'Kulgam', 'Kullu', 'Kupwara', 'Kurukshetra',
    'Kurung Kumey', 'Kushinagar', 'Kutch', 'Lahaul and Spiti', 'Lakhimpur',
    'Lakhimpur Kheri', 'Lakhisarai', 'Lalitpur', 'Latehar', 'Lawngtlai',
    'Leh', 'Lepa Rada', 'Lohardaga', 'Lohit', 'Longding',
    'Longleng', 'Lower Dibang Valley', 'Lower Siang', 'Lower Subansiri', 'Lunglei',
    'Madhepura', 'Madhubani', 'Maharajganj', 'Mahasamund', 'Mahendragarh',
    'Mahesana', 'Mahoba', 'Mainpuri', 'Majuli', 'Malappuram',
    'Maldah', 'Malkangiri', 'Mamit', 'Mancherial', 'Mandi',
    'Mandla', 'Mandsaur', 'Mandya', 'Mansa', 'Marigaon',
    'Mathura', 'Mau', 'Mayurbhanj', 'Medak', 'Medchal–Malkajgiri',
    'Mehsana', 'Mewat', 'Mirzapur', 'Moga', 'Mokokchung',
    'Mon', 'Morbi', 'Morena', 'Morigaon', 'Muktsar',
    'Mungeli', 'Munger', 'Murshidabad', 'Muzaffarpur', 'Nabarangpur',
    'Nadia', 'Nagaon', 'Nagapattinam', 'Nagarkurnool', 'Nagaur',
    'Nainital', 'Nalanda', 'Nalbari', 'Nalgonda', 'Namakkal',
    'Namsai', 'Nandurbar', 'Narayanpet', 'Narmada', 'Narsinghpur',
    'Navsari', 'Nawada', 'Nayagarh', 'Neemuch', 'New Delhi',
    'Nilgiris', 'Nirmal', 'Nizamabad', 'Noney', 'North 24 Parganas',
    'North Delhi', 'North East Delhi', 'North Garo Hills', 'North Goa', 'North Sikkim',
    'North Tripura', 'North West Delhi', 'Nuapada', 'Osmanabad', 'Pakur',
    'Palakkad', 'Palamu', 'Pali', 'Palwal', 'Panchkula',
    'Panchmahal', 'Panipat', 'Panna', 'Papum Pare', 'Parbhani',
    'Paschim Bardhaman', 'Paschim Medinipur', 'Pathanamthitta', 'Pathankot', 'Pauri Garhwal',
    'Peddapalli', 'Perambalur', 'Peren', 'Phek', 'Pherzawl',
    'Pilibhit', 'Pithoragarh', 'Poonch', 'Porbandar', 'Prakasam',
    'Pratapgarh', 'Pudukkottai', 'Pulwama', 'Purba Bardhaman', 'Purba Medinipur',
    'Puri', 'Purnia', 'Purulia', 'Raebareli', 'Raichur',
    'Raigad', 'Raigarh', 'Raisen', 'Rajanna Sircilla', 'Rajgarh',
    'Rajnandgaon', 'Rajouri', 'Rajsamand', 'Ramanagara', 'Ramanathapuram',
    'Ramban', 'Ramgarh', 'Rampur', 'Ramtek', 'Ranga Reddy',
    'Ranibennur', 'Ratlam', 'Ratnagiri', 'Rayagada', 'Reasi',
    'Rewa', 'Rewari', 'Ri Bhoi', 'Rohtas', 'Rudraprayag',
    'Rupnagar', 'Sabarkantha', 'Sagar', 'Saharsa', 'Sahibganj',
    'Saiha', 'Samastipur', 'Samba', 'Sambalpur', 'Sambhal',
    'Sangareddy', 'Sangrur', 'Sant Kabir Nagar', 'Saran', 'Satara',
    'Satna', 'Sawai Madhopur', 'Sehore', 'Senapati', 'Seoni',
    'Seraikela Kharsawan', 'Serchhip', 'Shahdara', 'Shahdol', 'Shahjahanpur',
    'Shajapur', 'Shamli', 'Sheikhpura', 'Sheohar', 'Sheopur',
    'Shivamogga', 'Shivpuri', 'Shopian', 'Shravasti', 'Siddharthnagar',
    'Siddipet', 'Sikar', 'Simdega', 'Sindhudurg', 'Singrauli',
    'Sirmaur', 'Sirohi', 'Sirsa', 'Sitamarhi', 'Sitapur',
    'Sivaganga', 'Sivasagar', 'Siwan', 'Solan', 'Sonbhadra',
    'Sonipat', 'Sonitpur', 'South 24 Parganas', 'South Delhi', 'South East Delhi',
    'South Garo Hills', 'South Salmara-Mankachar', 'South Tripura', 'South West Delhi', 'Sri Ganganagar',
    'Sri Potti Sriramulu Nellore', 'Srikakulam', 'Subarnapur', 'Sukma', 'Sultanpur',
    'Sundargarh', 'Supaul', 'Surajpur', 'Surendranagar', 'Surguja',
    'Suryapet', 'Tamenglong', 'Tapi', 'Tarn Taran', 'Tawang',
    'Tehri Garhwal', 'Tengnoupal', 'Thanjavur', 'The Dangs', 'Theni',
    'Thoothukudi', 'Thoubal', 'Thrissur', 'Tikamgarh', 'Tinsukia',
    'Tirap', 'Tiruvallur', 'Tiruvannamalai', 'Tonk', 'Tuensang',
    'Tumakuru', 'Tura', 'Udalguri', 'Udham Singh Nagar', 'Udhampur',
    'Udupi', 'Ukhrul', 'Umaria', 'Una', 'Unnao',
    'Upper Siang', 'Upper Subansiri', 'Uttar Dinajpur', 'Uttara Kannada', 'Uttarkashi',
    'Vaishali', 'Valsad', 'Vellore', 'Vidisha', 'Vikarabad',
    'Viluppuram', 'Virudhunagar', 'Vizianagaram', 'Wanaparthy', 'Warangal Urban',
    'Wardha', 'Washim', 'Wayanad', 'West Champaran', 'West Delhi',
    'West Garo Hills', 'West Godavari', 'West Jaintia Hills', 'West Kameng', 'West Karbi Anglong',
    'West Khasi Hills', 'West Siang', 'West Sikkim', 'West Singhbhum', 'West Tripura',
    'Wokha', 'Yadadri Bhuvanagiri', 'Yamunanagar', 'Yavatmal', 'Zunheboto'
  ];